//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackMe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.DeviceImages = new HashSet<DeviceImage>();
            this.Tracks = new HashSet<Track>();
            this.UserDevices = new HashSet<UserDevice>();
        }
    
        public int DeviceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DeviceTypeId { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual ICollection<DeviceImage> DeviceImages { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
        public virtual ICollection<UserDevice> UserDevices { get; set; }
    }
}
