//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackMe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.DeviceImages = new HashSet<DeviceImage>();
        }
    
        public int ImageId { get; set; }
        public string FileName { get; set; }
        public string ImageKey { get; set; }
    
        public virtual ICollection<DeviceImage> DeviceImages { get; set; }
    }
}
